### PR TITLE
Trigger delayed start test with security enabled

### PR DESCRIPTION
**Pull request by cherrycl**
1. Trigger delayed start test with security enabled
2. Remove backward test related script

Signed-off-by: Cherry Wang <cherry@iotechsys.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [X] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

### CODE REVIEW

**Comment by cherrycl** [comment]
Waiting [edgex-taf #709](https://github.com/edgexfoundry/edgex-taf/pull/709) is merged.

**Comment by cherrycl** [comment]
recheck

**Comment by cherrycl** [comment]
@jumpingliu The Jenkins check is passed, please help to review when you have time. Thanks.

**Review by jumpingliu — APPROVED** [review]
LGTM

**Pull request merged**
